### ISSUE TITLE
react-good-input breaks isomorphic builds

### ISSUE THREAD

**Issue by glortho** [DigitalGlobe/react-good-input#5]
It appears that since css gets bundled in with this lib, all the references to `window` and `document` etc. in style-loader (and maybe other css loaders) throw errors when we try to render server-side.

I've heard rumors of an isomorphic style loader, which may or may not fix everything. It might not be a bad idea to extract the styles into a separate stylesheet that users can import as needed. Not sure.

**Comment by winrox** [comment]
fixed in 1.0.0 release
